[project]
name = "26L-SPZC-ids-explainability"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "Paweł Kochański", email = "pawilioxion@gmail.com" }]
dependencies = [
    "numpy>=2.4.6",
    "polars>=1.40.1",
    "scikit-learn>=1.8.0",
    "imblearn>=0.0",
    "torch>=2.12.0",
    "lightning>=2.6.1",
    "dtreeviz>=2.3.2",
]
requires-python = "==3.13.*"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = ["-e file:///${PROJECT_ROOT}/#egg=26L-SPZC-ids-explainability"]

[[tool.pdm.source]]
name = "private"
url = "https://download.pytorch.org/whl/cpu"
include_packages = ["torch", "torchvision"]
exclude_packages = ["*"]
